### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by ghost** [andrew-kurin/django-authorizenet#1]
It would be nice/useful if django-authorizenet would be made pip installable.

**Comment by andrew-kurin** [comment]
for now you can use
pip install -e git://github.com/zen4ever/django-authorizenet.git#egg=django-authorizenet
I will make a first release and upload the package on PyPi soon.

**Comment by ghost** [comment]
Great. It's certainly a package which deserves being on PyPI.

**Comment by andrew-kurin** [comment]
Released django-authorizenet 1.0 on PyPi,
now you can use **pip install django-authorizenet**

**Comment by ghost** [comment]
great, thanks ... now we need more people using it and start contributing :)
