### ISSUE TITLE
Allow CIM helper function return value extension without breaking code

### ISSUE THREAD

**Issue by treyhunner** [andrew-kurin/django-authorizenet#11]
Currently the `cim.add_profile`, `cim.get_profile`, and similar CIM functions return a tuple of mixed types.  This helper function return method is flawed because:
1. Some of the values in these tuples may be unused in many use cases but are necessary in others (`shipping_profile_ids`)
2. If the CIM API is extended or more features are added to django-authorizenet more values may be added to this tuple which could break existing code that unpacks this tuple

I think a more flexible data structure should be returned.  A `dict` or a custom `class` object would allow new values to be added without breaking existing code.

Any ideas regarding this issue are welcome.

**Comment by andrew-kurin** [comment]
I agree that tuple is too inflexible at this point.

It seems that add_profile returns just ids of billing/shipping profiles, while get_profile returns actual profiles (which are dicts).
I think `dict` would be flexible enough, and more appropriate in this case.
It looks like custom `class` would make more sense for Billing and Shipping profiles themselves.

Also, if we decide to rewrite `cim.add_profile`, `cim.get_profile` to return `dict` or `class`, we would probably want to rewrite other functions in this module to return the same structure to be consistent.

**Comment by treyhunner** [comment]
As a solution to this issue, I'll be merging 3d652b838337acaf7433726c9079ae53644c464e into master in a few days unless objections arise.

This will unfortunately break existing code that uses CIM helper functions.

**Comment by treyhunner** [comment]
Merged: 3d652b838337acaf7433726c9079ae53644c464e
