### ISSUE TITLE
CreateTransactionRequest not works for 'void' type of transaction (CIM api).

### ISSUE THREAD

**Issue by piterimov** [andrew-kurin/django-authorizenet#12]
CreateTransactionRequest require 'amount' parameter for all type of transactions. As described here http://www.authorize.net/support/CIM_XML_guide.pdf  'amount' not needed for 'void' transaction. But CreateTransactionRequest create '&lt;amount&gt;...&lt;/amount&gt;' tags for 'void' also. Because of this, authorize.net return the error message:

"The element 'profileTransVoid' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'amount' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'customerProfileId, customerPaymentProfileId, customerShippingAddressId, transId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd" .
And transaction doesn't pass.

**Comment by andrew-kurin** [comment]
Could you please try this fix in the branch 'ticket12' and see if it works for you?

**Comment by piterimov** [comment]
Yes, it works great. Only need to correct the typo in line 697 <code>if amount and self.transaction_type != "Void":</code> from <code>amount</code> to <code>self.amount</code> and it will work fine.

Thank you!
